name: poswork
description: Simple POS application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  bloc: ^9.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.13.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  bloc_lint: ^0.3.7
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.22
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
  fonts:
    enabled: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
